### ISSUE TITLE
Headless Chrome

### ISSUE THREAD

**Issue by mycure** [watir/nerodia#7]
Hi,

I cannot find how to set the Chrome browser in headless mode. I've looked in the source code and there seems to be a way through a DesiredCapabilities class. At the same time, code has been removed following the introduction of the headless capability in Selenium so not sure where to look.

`import nerodia`
`browser = nerodia.browser.Browser(browser = 'chrome', ... [to activate headless])`

Thanks.

**Comment by lmtierney** [comment]
Hi there. Sorry for not having the examples or documentation fully updated yet, we're working on that.

Anything that would be a browser option would go inside the `options` key, for example:

```
browser = Browser('chrome', options={'headless': True})
```

You can also pass a Selenium Options class itself.

```
from selenium.webdriver.chrome.options import Options
opts = Options()
opts.set_headless()
browser = Browser('chrome', options=opts)
```

**Comment by gauravVanvari** [comment]
If I use approach 1,  browser still opens up 
` browser = Browser('chrome', options={'headless': True})`

If I use approach 2, 
```
from selenium.webdriver.chrome.options import Options
opts = Options()
opts.set_headless()
browser = Browser('chrome', options=opts)
```
I get the following error:
```
Traceback (most recent call last):
  File "example.py", line 23, in getBrowser
    return Browser(browser = web_browser, options = opts)
  File "i/pythonENV/lib/python2.7/site-packages/nerodia/browser.py", line 36, in __init__
    self.driver = module.WebDriver(**caps.kwargs)
  File "/pythonENV/lib/python2.7/site-packages/nerodia/capabilities.py", line 30, in kwargs
    self._process_arguments()
  File "/pythonENV/lib/python2.7/site-packages/nerodia/capabilities.py", line 45, in _process_arguments
    self._process_browser_options()
  File "/pythonENV/lib/python2.7/site-packages/nerodia/capabilities.py", line 57, in _process_browser_options
    self._process_firefox_options(browser_options)
  File "/pythonENV/lib/python2.7/site-packages/nerodia/capabilities.py", line 95, in _process_firefox_options
    if 'args' in opts:
TypeError: argument of type 'Options' is not iterable
```

**Comment by lmtierney** [comment]
Both of these approaches work fine for me. What version are you using?

**Comment by gauravVanvari** [comment]
I realized this right after posting the error. My bad. 
thank you, for the prompt response. 
Also , are there no headless options for firefox ?

**Comment by gauravVanvari** [comment]
On using  `b = Browser('chrome', options={'headless': True})` , i get -->
```
  File "/pythonENV/example.py", line 32, in example
    username.value = user_name
  File "/pythonENV/lib/python2.7/site-packages/nerodia/user_editable.py", line 19, in value
    self.set(*args)
  File "/pythonENV/lib/python2.7/site-packages/nerodia/user_editable.py", line 11, in set
    self._element_call(func, self.wait_for_writable)
  File "/pythonENV/lib/python2.7/site-packages/nerodia/elements/element.py", line 647, in _element_call
    return self._element_call_check(exist_check, method)
  File "/pythonENV/lib/python2.7/site-packages/nerodia/elements/element.py", line 666, in _element_call_check
    raise self._unknown_exception(msg)
nerodia.exception.UnknownObjectException: timed out after 30 seconds, waiting for #<TextField: located: False; {'tag_name': 'input', 'name': 'username'}> to be located
```
To login in have to enter the username first , and it complains but without headless it works fine.

**Comment by lmtierney** [comment]
@gauravVanvari if it works without headless but not when headless it's a chrome/chromedriver issue

Please log any Chrome & Chromedriver issues with Chromium: https://bugs.chromium.org/p/chromedriver/issues/list
